server:
  port: 8101
spring:
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
      bigdata:  #数据源1
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/adb1?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password: nick1215
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxWait: 60000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        statViewServlet:
          enabled: true
          urlPattern: /druid/*
          #login-username: admin
          #login-password: admin
        filters: stat,wall,log4j2
      plat:  #数据源2
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/adb2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password: nick1215
        initialSize: 10
        maxActive: 100
        minIdle: 10
        maxWait: 60000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        statViewServlet:
          enabled: true
          urlPattern: /druid/*
          #login-username: admin
          #login-password: admin
        filters: stat,wall,log4j2
#      plat:  #数据源oracle
#        driverClassName: oracle.jdbc.OracleDriver
#        url: jdbc:oracle:thin:@192.168.100.233:1521:oracle
#        username: qcs
#        password: manager
#        initialSize: 10
#        maxActive: 100
#        minIdle: 10
#        maxWait: 60000
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1 FROM DUAL
#        validationQueryTimeout: 10000
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        statViewServlet:
#          enabled: true
#          urlPattern: /druid/*
#          #login-username: admin
#          #login-password: admin
#        filters: stat,wall,log4j2
    #jta相关参数配置
  jta:
    log-dir: classpath:tx-logs
    transaction-manager-id: txManager



#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wisesoft.*.entity
  typeEnumsPackage: com.baomidou.springboot.db.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: UUID
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: not_empty
    #驼峰下划线转换
    column-underline: true
    #刷新mapper 调试神器
    #    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: Y
    logic-not-delete-value: N
  #    sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level:
    root: info
    com.atomikos: debug
  path: logs/
  file: atomikos.log